/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */




/**
 *
 * @author Marianne
 */
public class HomePage extends javax.swing.JFrame {       
        

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
         
        
         if(coffeeBtn.isEnabled()){
             
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScollContainer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LogoName = new javax.swing.JLabel();
        coffeeBtn = new javax.swing.JButton();
        TeaBtn = new javax.swing.JButton();
        DrinksBtn = new javax.swing.JButton();
        FoodBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ScollContainer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ScollContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setFocusable(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 220, 170));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 170));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 170));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 220, 170));

        jScrollPane2.setViewportView(jPanel3);

        ScollContainer.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1010, 930, 240));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 220, 170));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 130));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 170));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 170));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 220, 170));

        jScrollPane3.setViewportView(jPanel9);

        ScollContainer.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 930, 240));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 220, 170));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 170));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 170));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 220, 170));

        jScrollPane4.setViewportView(jPanel15);

        ScollContainer.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 930, 230));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 220, 170));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 220, 170));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 170));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 220, 170));

        jScrollPane5.setViewportView(jPanel21);

        ScollContainer.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 930, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel2.setText("Featured Coffe");
        ScollContainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 292, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel3.setText("Featured Food");
        ScollContainer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 960, 292, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel4.setText("Featured Drinks");
        ScollContainer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 292, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel5.setText("Featured Tea");
        ScollContainer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 292, 40));

        jScrollPane1.setViewportView(ScollContainer);

        Container.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1050, 600));

        LogoName.setBackground(new java.awt.Color(255, 255, 255));
        LogoName.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        LogoName.setText("Elysian");
        LogoName.setToolTipText("");
        Container.add(LogoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 229, 76));

        coffeeBtn.setText("Coffee");
        coffeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeBtnActionPerformed(evt);
            }
        });
        Container.add(coffeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        TeaBtn.setText("Tea");
        TeaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaBtnActionPerformed(evt);
            }
        });
        Container.add(TeaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        DrinksBtn.setText("Drinks");
        DrinksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksBtnActionPerformed(evt);
            }
        });
        Container.add(DrinksBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        FoodBtn.setText("Food");
        FoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodBtnActionPerformed(evt);
            }
        });
        Container.add(FoodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        AdminBtn.setText("Admin");
        Container.add(AdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodBtnActionPerformed
        // TODO add your handling code here:
        FoodDashBoard fd = new FoodDashBoard();
        fd.setVisible(true);
        HomePage hp = new HomePage();
        hp.setVisible(false);
    }//GEN-LAST:event_FoodBtnActionPerformed

    private void coffeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeBtnActionPerformed
        // TODO add your handling code here:
        HomePage hp = new HomePage();
        hp.setVisible(false);
        CoffeeDashboad cd = new CoffeeDashboad();
        cd.setVisible(true);
    }//GEN-LAST:event_coffeeBtnActionPerformed

    private void TeaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaBtnActionPerformed
        // TODO add your handling code here:
        TeaDashBoard td = new TeaDashBoard();
        td.setVisible(true);
        HomePage hp = new HomePage();
        hp.setVisible(false);
    }//GEN-LAST:event_TeaBtnActionPerformed

    private void DrinksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksBtnActionPerformed
        // TODO add your handling code here:
        DrinksDashBoard dD = new DrinksDashBoard();
        dD.setVisible(true);
        HomePage hp = new HomePage();
        hp.setVisible(false);
    }//GEN-LAST:event_DrinksBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JPanel Container;
    private javax.swing.JButton DrinksBtn;
    private javax.swing.JButton FoodBtn;
    private javax.swing.JLabel LogoName;
    private javax.swing.JPanel ScollContainer;
    private javax.swing.JButton TeaBtn;
    private javax.swing.JButton coffeeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables


}
