/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*; 
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Marianne
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoName1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameF = new javax.swing.JTextField();
        passwordF = new javax.swing.JPasswordField();
        loginB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ShowPass = new javax.swing.JCheckBox();
        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoName1.setBackground(new java.awt.Color(255, 255, 255));
        LogoName1.setFont(new java.awt.Font("Vivaldi", 3, 48)); // NOI18N
        LogoName1.setForeground(new java.awt.Color(255, 255, 255));
        LogoName1.setText("Elysian");
        LogoName1.setToolTipText("");
        getContentPane().add(LogoName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 150, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 0, -1, 230));

        jLabel3.setText("USERNAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 32, -1, -1));
        jPanel1.add(usernameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 66, 190, -1));

        passwordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFActionPerformed(evt);
            }
        });
        jPanel1.add(passwordF, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 135, 190, -1));

        loginB.setText("LOG IN");
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });
        jPanel1.add(loginB, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 181, -1, -1));

        jLabel4.setText("PASSWORD");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 106, -1, -1));

        ShowPass.setText("Show Password");
        ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 175, -1, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 400, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brgcoffee.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_passwordFActionPerformed

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        // TODO add your handling code here:
 String username = usernameF.getText();
    String password = new String(passwordF.getPassword());  // Use getPassword() to retrieve the password

    // Validate if username and password are empty
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter both username and password.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Database connection details
    String url = "jdbc:mysql://localhost:3306/oop";   // Your database URL
    String dbUser = "root";  // Your database username
    String dbPassword = "";  // Your database password

    // SQL query to check user credentials
    String query = "SELECT * FROM user WHERE username = ? AND password = ?";

    try (Connection connection = DriverManager.getConnection(url, dbUser, dbPassword);  // Establish database connection
         PreparedStatement stmt = (PreparedStatement) connection.prepareStatement(query)) {
        
        // Set parameters for username and password
        stmt.setString(1, username);
        stmt.setString(2, password);  // In a real app, hash the password before checking
        
        // Execute the query
        ResultSet resultSet = stmt.executeQuery();

        // If a matching user is found
        if (resultSet.next()) {
            // User found, login success
            JOptionPane.showMessageDialog(null, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            // You can add code here to transition to the next window after successful login
            HomePage hp = new HomePage();
            hp.setVisible(true);
             //HomePage homePage = new HomePage();  // Create a new HomePage instance
            //homePage.setVisible(true);  // Show the HomePage
            this.dispose();  // Close the current Login window
        } else {
            // No matching user found
            JOptionPane.showMessageDialog(null, "Invalid username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }   catch (SQLException ex) { 
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_loginBActionPerformed

    private void ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassActionPerformed
        // TODO add your handling code here:
        if(ShowPass.isSelected()){
            passwordF.setEchoChar('\0');
        }
    }//GEN-LAST:event_ShowPassActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here.
        usernameF.setText("");
        passwordF.setText(null);
        
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoName1;
    private javax.swing.JCheckBox ShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginB;
    private javax.swing.JPasswordField passwordF;
    private javax.swing.JButton reset;
    private javax.swing.JTextField usernameF;
    // End of variables declaration//GEN-END:variables
}
