
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marianne
 */
public class TeaDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form TeaDashBoard
     */
    public TeaDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TeaDashBoard = new javax.swing.JPanel();
        ChaiTea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tname4 = new javax.swing.JLabel();
        Price4 = new javax.swing.JLabel();
        AddBtn4 = new javax.swing.JButton();
        HerbalTea = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Price8 = new javax.swing.JLabel();
        AddBtn8 = new javax.swing.JButton();
        Pu_erh_Tea = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        Price15 = new javax.swing.JLabel();
        AddBtn15 = new javax.swing.JButton();
        MintTea = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Price12 = new javax.swing.JLabel();
        AddBtn12 = new javax.swing.JButton();
        GenMaichaTea = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Tname3 = new javax.swing.JLabel();
        Price3 = new javax.swing.JLabel();
        AddBtn3 = new javax.swing.JButton();
        EarlyGreyTea = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Tname2 = new javax.swing.JLabel();
        Price2 = new javax.swing.JLabel();
        AddBtn2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Tname1 = new javax.swing.JLabel();
        Price1 = new javax.swing.JLabel();
        AddBtn1 = new javax.swing.JButton();
        HibiscusTea = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        Price7 = new javax.swing.JLabel();
        AddBtn7 = new javax.swing.JButton();
        JasmineTea = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Price6 = new javax.swing.JLabel();
        AddBtn6 = new javax.swing.JButton();
        MatchaTea = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Tname5 = new javax.swing.JLabel();
        Price5 = new javax.swing.JLabel();
        AddBtn5 = new javax.swing.JButton();
        CharmomoleTea = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        Price11 = new javax.swing.JLabel();
        AddBtn11 = new javax.swing.JButton();
        WhiteTea = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        Price10 = new javax.swing.JLabel();
        AddBtn10 = new javax.swing.JButton();
        RooibosTea = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        Price9 = new javax.swing.JLabel();
        AddBtn9 = new javax.swing.JButton();
        OolongTea = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        Price14 = new javax.swing.JLabel();
        AddBtn14 = new javax.swing.JButton();
        DarjeelingTea = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        Price13 = new javax.swing.JLabel();
        AddBtn13 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Price16 = new javax.swing.JLabel();
        AddBtn16 = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TeaDashBoard.setBackground(new java.awt.Color(255, 255, 255));
        TeaDashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChaiTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ChaiTea.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 190));

        jLabel2.setText("Name ");
        ChaiTea.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel3.setText("Price");
        ChaiTea.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        Tname4.setText("Chai Tea");
        ChaiTea.add(Tname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price4.setText("130");
        ChaiTea.add(Price4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn4.setText("Add");
        ChaiTea.add(AddBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(ChaiTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 220, 310));

        HerbalTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Herbal Tea.jpg"))); // NOI18N
        HerbalTea.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel7.setText("Name ");
        HerbalTea.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel8.setText("Price");
        HerbalTea.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel9.setText("Herbal Tea");
        HerbalTea.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price8.setText("130");
        HerbalTea.add(Price8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn8.setText("Add");
        AddBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn8ActionPerformed(evt);
            }
        });
        HerbalTea.add(AddBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(HerbalTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 220, 310));

        Pu_erh_Tea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pu-erh tea.jpg"))); // NOI18N
        Pu_erh_Tea.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel132.setText("Name ");
        Pu_erh_Tea.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel133.setText("Price");
        Pu_erh_Tea.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel134.setText("Pu - erh Tea");
        Pu_erh_Tea.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price15.setText("130");
        Pu_erh_Tea.add(Price15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn15.setText("Add");
        Pu_erh_Tea.add(AddBtn15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(Pu_erh_Tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 1010, 220, 310));

        MintTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mint tea_1.jpg"))); // NOI18N
        MintTea.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel27.setText("Name ");
        MintTea.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel28.setText("Price");
        MintTea.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel29.setText("Mint Tea");
        MintTea.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price12.setText("130");
        MintTea.add(Price12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn12.setText("Add");
        MintTea.add(AddBtn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(MintTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 680, 220, 310));

        GenMaichaTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Genmaicha.jpg"))); // NOI18N
        GenMaichaTea.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel17.setText("Name ");
        GenMaichaTea.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel18.setText("Price");
        GenMaichaTea.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        Tname3.setText("Genmaicha tea");
        GenMaichaTea.add(Tname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price3.setText("130");
        GenMaichaTea.add(Price3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn3.setText("Add");
        AddBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn3ActionPerformed(evt);
            }
        });
        GenMaichaTea.add(AddBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(GenMaichaTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 220, 310));

        EarlyGreyTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Earl Grey.jpg"))); // NOI18N
        EarlyGreyTea.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel12.setText("Name ");
        EarlyGreyTea.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel13.setText("Price");
        EarlyGreyTea.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        Tname2.setText("Early Grey ");
        EarlyGreyTea.add(Tname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price2.setText("130");
        EarlyGreyTea.add(Price2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn2.setText("Add");
        EarlyGreyTea.add(AddBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(EarlyGreyTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 220, 310));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Chai tea.jpg"))); // NOI18N
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 190));

        jLabel22.setText("Name ");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel23.setText("Price");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        Tname1.setText("Chai Tea");
        jPanel7.add(Tname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price1.setText("130");
        jPanel7.add(Price1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn1.setText("Add");
        AddBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn1ActionPerformed(evt);
            }
        });
        jPanel7.add(AddBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 220, 310));

        HibiscusTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hibiscus Tea.jpg"))); // NOI18N
        HibiscusTea.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel42.setText("Name ");
        HibiscusTea.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel43.setText("Price");
        HibiscusTea.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel44.setText("Hibiscus Tea");
        HibiscusTea.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price7.setText("130");
        HibiscusTea.add(Price7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn7.setText("Add");
        HibiscusTea.add(AddBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(HibiscusTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 220, 310));

        JasmineTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Jasmine Tea.jpg"))); // NOI18N
        JasmineTea.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel32.setText("Name ");
        JasmineTea.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel33.setText("Price");
        JasmineTea.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel34.setText("Jasmine Tea");
        JasmineTea.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price6.setText("130");
        JasmineTea.add(Price6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn6.setText("Add");
        AddBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtn6ActionPerformed(evt);
            }
        });
        JasmineTea.add(AddBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(JasmineTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 220, 310));

        MatchaTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Matcha.jpg"))); // NOI18N
        MatchaTea.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel47.setText("Name ");
        MatchaTea.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel48.setText("Price");
        MatchaTea.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        Tname5.setText("Matcha Tea");
        MatchaTea.add(Tname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price5.setText("130");
        MatchaTea.add(Price5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn5.setText("Add");
        MatchaTea.add(AddBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(MatchaTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 220, 310));

        CharmomoleTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Charmomile Tea.jpg"))); // NOI18N
        CharmomoleTea.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 350, 190));

        jLabel62.setText("Name ");
        CharmomoleTea.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel63.setText("Price");
        CharmomoleTea.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel64.setText("Charmomile Tea ");
        CharmomoleTea.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price11.setText("130");
        CharmomoleTea.add(Price11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn11.setText("Add");
        CharmomoleTea.add(AddBtn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(CharmomoleTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 680, 220, 310));

        WhiteTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/White Tea.jpg"))); // NOI18N
        WhiteTea.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel57.setText("Name ");
        WhiteTea.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel58.setText("Price");
        WhiteTea.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel59.setText("White Tea");
        WhiteTea.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price10.setText("130");
        WhiteTea.add(Price10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn10.setText("Add");
        WhiteTea.add(AddBtn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(WhiteTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, 220, 310));

        RooibosTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rooibos Tea.jpeg"))); // NOI18N
        RooibosTea.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel67.setText("Name ");
        RooibosTea.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel68.setText("Price");
        RooibosTea.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel69.setText("Rooibos Tea");
        RooibosTea.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price9.setText("130");
        RooibosTea.add(Price9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn9.setText("Add");
        RooibosTea.add(AddBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(RooibosTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 220, 310));

        OolongTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Oolong Tea.jpg"))); // NOI18N
        OolongTea.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel77.setText("Name ");
        OolongTea.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel78.setText("Price");
        OolongTea.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel79.setText("Oolong Tea");
        OolongTea.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price14.setText("130");
        OolongTea.add(Price14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn14.setText("Add");
        OolongTea.add(AddBtn14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(OolongTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 1010, 220, 310));

        DarjeelingTea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Darjeeling Tea.jpg"))); // NOI18N
        DarjeelingTea.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 190));

        jLabel72.setText("Name ");
        DarjeelingTea.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel73.setText("Price");
        DarjeelingTea.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel74.setText("Darjeeling Tea");
        DarjeelingTea.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price13.setText("130");
        DarjeelingTea.add(Price13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn13.setText("Add");
        DarjeelingTea.add(AddBtn13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(DarjeelingTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 1010, 220, 310));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Assam Tea.jpg"))); // NOI18N
        jPanel13.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 190));

        jLabel52.setText("Name ");
        jPanel13.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 30));

        jLabel53.setText("Price");
        jPanel13.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel54.setText("Assam Tea");
        jPanel13.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        Price16.setText("130");
        jPanel13.add(Price16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        AddBtn16.setText("Add");
        jPanel13.add(AddBtn16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        TeaDashBoard.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1010, 220, 310));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brgcoffee.jpg"))); // NOI18N
        BackgroundImage.setText("jLabel36");
        TeaDashBoard.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 1340));

        jScrollPane1.setViewportView(TeaDashBoard);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 1040, 580));

        jLabel37.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Tea Menu");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 130, 40));

        jButton1.setText("Coffee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        jButton2.setText("Tea");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 70, -1));

        jButton3.setText("Drinks");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, -1, -1));

        jButton4.setText("Pastry");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 660, -1, -1));

        jButton5.setText("Dishes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, -1, -1));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton6.setText("Total");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 630, 120, 40));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brgcoffee.jpg"))); // NOI18N
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void AddBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn3ActionPerformed

    private void AddBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn6ActionPerformed

    private void AddBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtn8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        CoffeeDashboard cdb = new CoffeeDashboard();
        cdb.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        TeaDashBoard tdb = new TeaDashBoard();
        tdb.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        PastryDashBoard2 pdb = new PastryDashBoard2();
        pdb.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        FoodDashBoard fdb = new FoodDashBoard();
        fdb.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        DrinksDashBoard ddb = new DrinksDashBoard();
        ddb.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        OrderList OL = new OrderList();
        OL.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    @SuppressWarnings("empty-statement")
    private void AddBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtn1ActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/oop";   
        String user = "root";  
        String password = ""; 

        String TeaName = Tname1.getText();
        String price = Price1.getText();
        

      

        // Validate user input
        if (TeaName.isEmpty() || price == null) {
            JOptionPane.showMessageDialog(null, "Please fill out all the required information.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop execution if validation fails
        }

        // Validate price is numeric
        try {
            Double.parseDouble(price);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Price must be a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop execution if validation fails
        }

        String query = "INSERT INTO `tea` (`TeaName`, `price`) VALUES (?, ?)";
        Connection connection = null;
        PreparedStatement stmt = null;

        try {
            connection = (Connection) DriverManager.getConnection(url, user, password);
            stmt = connection.prepareStatement(query);

            // Set parameter values
            stmt.setString(1, TeaName);             
            stmt.setString(2, price);  
            

    
            // Execute query
            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Tea  added successfully!");
            }

        }catch (Exception e){
                    System.out.println("walang koneksyon");;
                }
                  finally {
            // Proper resource cleanup
            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e){
                    System.out.println("walang koneksyon");;
                }
            } 
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e){
                    System.out.println("walang koneksyon");;
                }
            } // Log closing error
        }
    }//GEN-LAST:event_AddBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeaDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeaDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeaDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeaDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeaDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn1;
    private javax.swing.JButton AddBtn10;
    private javax.swing.JButton AddBtn11;
    private javax.swing.JButton AddBtn12;
    private javax.swing.JButton AddBtn13;
    private javax.swing.JButton AddBtn14;
    private javax.swing.JButton AddBtn15;
    private javax.swing.JButton AddBtn16;
    private javax.swing.JButton AddBtn2;
    private javax.swing.JButton AddBtn3;
    private javax.swing.JButton AddBtn4;
    private javax.swing.JButton AddBtn5;
    private javax.swing.JButton AddBtn6;
    private javax.swing.JButton AddBtn7;
    private javax.swing.JButton AddBtn8;
    private javax.swing.JButton AddBtn9;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel ChaiTea;
    private javax.swing.JPanel CharmomoleTea;
    private javax.swing.JPanel DarjeelingTea;
    private javax.swing.JPanel EarlyGreyTea;
    private javax.swing.JPanel GenMaichaTea;
    private javax.swing.JPanel HerbalTea;
    private javax.swing.JPanel HibiscusTea;
    private javax.swing.JPanel JasmineTea;
    private javax.swing.JPanel MatchaTea;
    private javax.swing.JPanel MintTea;
    private javax.swing.JPanel OolongTea;
    private javax.swing.JLabel Price1;
    private javax.swing.JLabel Price10;
    private javax.swing.JLabel Price11;
    private javax.swing.JLabel Price12;
    private javax.swing.JLabel Price13;
    private javax.swing.JLabel Price14;
    private javax.swing.JLabel Price15;
    private javax.swing.JLabel Price16;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel Price3;
    private javax.swing.JLabel Price4;
    private javax.swing.JLabel Price5;
    private javax.swing.JLabel Price6;
    private javax.swing.JLabel Price7;
    private javax.swing.JLabel Price8;
    private javax.swing.JLabel Price9;
    private javax.swing.JPanel Pu_erh_Tea;
    private javax.swing.JPanel RooibosTea;
    private javax.swing.JPanel TeaDashBoard;
    private javax.swing.JLabel Tname1;
    private javax.swing.JLabel Tname2;
    private javax.swing.JLabel Tname3;
    private javax.swing.JLabel Tname4;
    private javax.swing.JLabel Tname5;
    private javax.swing.JPanel WhiteTea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
